### ISSUE TITLE
image uses unsupported features: 0x38

### ISSUE THREAD

**Issue by alexeysmovzh** [wetopi/docker-volume-rbd#4]
On volume creation i get following error message

```
docker volume create -d wetopi-rbd -o size=256 vol0
Error response from daemon: create vol0: VolumeDriver.Create: volume-rbd Name=vol0 Request=Create Message=unable to create ceph rbd image: exit status 6


dmesg | tail
[ 4186.766150] rbd: image vol0: image uses unsupported features: 0x38
```

What feature cause error message?
Can i disable it?

system information

```
ubuntu 18.04 bionic x64

docker plugin inspect wetopi-rbd | grep VER
                    "Name": "PLUGIN_VERSION",
                "PLUGIN_VERSION=1.0.1",


sudo ceph --version
ceph version 13.2.1 (5533ecdc0fda920179d7ad84e0aa65a127b20d77) mimic (stable)


docker info
Server Version: 18.06.1-ce
```

Thanks!

**Comment by sitamet** [comment]
Not sure what is causing the error
the rbd image create call is simple:

https://github.com/wetopi/docker-volume-rbd/blob/fd0b7cffdbd39df84c7393934d71c78d22182c2d/lib/rbd-driver-public.go#L143-L149

I suspect the problem is on the rbd client side (rbd driver is not passing features). Check the default features, and try to set them on ceph.conf. Take a look at https://tracker.ceph.com/issues/15000

**Comment by alexeysmovzh** [comment]
I tryed different values for ceph rbd image features.
It started working fine with  rbd_default_features = 7

Thank you for your answer!

```
cat ceph.conf

[global]
  ...
  rbd_default_features = 7

```
